kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: controlplane
nodes:
  - role: control-plane
    extraPortMappings:
      # Map the diarization Service NodePort to localhost:8080
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
